# Generated by Django 4.2.1 on 2023-05-15 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comment_is_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='authorname',
            field=models.CharField(default='aaaaa', max_length=1000),
            preserve_default=False,
        ),
    ]
