# Generated by Django 4.2 on 2023-05-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_gender_alter_profile_ban_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
