# Generated by Django 4.2 on 2023-05-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='tmp@gmail.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='male', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='master_key',
            field=models.IntegerField(default=0),
        ),
    ]
